channels:
 - conda-forge
dependencies:
 - r-base=4.1.3
 - r-tinytex 
 - r-kableextra
 - r-rmarkdown
 - r-bookdown
 - r-extrafont
 - r-extrafontdb
 - r-devtools
 - r-rcpp
 - r-rttf2pt1=1.3.8
 - r-httpuv #
 - r-promises #
 - r-later #
 - r-codetools #
 - libgcc-ng #
 - ncurses #
 - fonts-conda-forge