#!/bin/bash

# Stop on fail!
set -e

# Install biosketch packages 
Rscript - <<'EOF'
  library('devtools')
  library('extrafont')
  ttf_import(paths = '~/fonts', recursive = TRUE, pattern = NULL)
  biosketch_pkgs <- list('microtype', 'tabu', 'ulem', 'enumitem', 'titlesec')
  lapply(biosketch_pkgs, function (x) {
    tinytex::parse_install(text=paste('! LaTeX Error: File',
                                      paste0("`", x, ".sty'"),
                                      'not found.'))
  })
EOF

cp -r fonts/* /srv/conda/envs/notebook/fonts