#!/bin/bash

# Stop on fail!
set -e

Rscript -e "library('remotes')" 
Rscript -e "library('extrafont')"

#Rscript -e "remotes::install_version('Rttf2pt1', version = '1.3.8')"
Rscript -e "withr::with_libpaths(new = '/srv/conda/envs/notebook/lib/R/library' , devtools::install_github('wch/Rttf2pt1@000efae', upgrade = 'never', dependencies = TRUE))"

Rscript -e "font_install(fontpkg = 'arial', prompt = FALSE)"